language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true


services:
  - docker

before_install:
  - docker build -t dockerfonseka/dockergoapp:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
