language: go

go:
  - 1.9.x
  - 1.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true


services:
  - docker

install:
  - docker build -t dockerfonseka/dockergoapptwo:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
