language: go

go:
  - 1.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true


services:
  - docker

install:
  - docker build -t dockerfonseka/dockergoapptwo:latest .

deploy:
  provider: script
  script: ${GOPATH}/src/github.com/Niraj-Fonseka/go_docker_example/docker_push.sh
  on:
    branch: master
